version: '3'

services:
  registry:        
    image: chandug2310/e_bug_registry
    ports:
      - 9005:9005
   
  admin:        
    image: viji27/deliveryperson
    ports:
      - 8485:8485
     
  

  postgres:        
    image: postgres:13.3
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1359
      POSTGRES_DB: groceryDeliveryApp

    volumes:
      - pgdata:/var/lib/postgresql/data

 
volumes:
  pgdata:    
    
 

    

   
